version: 2
jobs:
  job1:
    docker:
      - image: circleci/node:10

    steps:
      - checkout
      - run: npm install
      - run: npm test

  job2:
    docker:
      - image: circleci/node:10

    steps:
      - checkout
      - run: cat README.md

workflows:
  version: 2
  parallel:
    jobs:
      - job1
      - job2
  serial:
    jobs:
      - job1
      - job2:
        requires:
          -job1
