only-pre-branches: &only-pre-branches
  filters:
    branches:
      only:
        - master
        - dev

version: 2
jobs:
  job1:
    docker:
      - image: circleci/node:10

    steps:
      - checkout
      - run: npm install
      - run: npm test

  job2:
    docker:
      - image: circleci/node:10

    steps:
      - checkout
      - run: cat README.md

workflows:
  version: 2
  parallel:
    jobs:
      - job1:
          <<: *only-pre-branches
      - job2:
          filters:
              branches:
                ignore: master
  serial:
    jobs:
      - job1
      - job2:
          requires:
            - job1
