only-pre-branches: &only-pre-branches
  filters:
    branches:
      only:
        - master
        - dev

executors:
  my-executor:
    environment:
      CUSTOM_ENV: executor
    docker:
      - image: circleci/ruby:2.5.1-node-browsers

version: 2
jobs:
  job1:
    docker:
      - image: circleci/node:10

    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: curl $API_URL

  job2:
    executor: my-executor
    steps:
      - run:
          name: Get env
          command: echo $CUSTOM_ENV
      - run:
          environment:
            CUSTOM_ENV: run
          name: Get Env with set env in run
          command: echo $CUSTOM_ENV
  
  job3:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: default shell test
          command: |
            set +e
            echo 'default shell'
            cd /test
            echo 'This is the default shell test with set e'
      - run:
          name: default shell with pipe
          command: |
            set +o pipefail
            pwd
            ls -al
            cd /test | echo 'this is a pipe'

workflows:
  version: 2
  parallel:
    jobs:
      - job1:
          <<: *only-pre-branches
      - approval:
          type: approval
          requires:
            - job1
      - job2:
          filters:
              branches:
                ignore: master
          requires:
            - approval
  serial:
    jobs:
      - job1
      - job2:
          requires:
            - job1
